version: '2'
services:

  web:
    build:
      context: .
      dockerfile: ./docker/arm/node-frontend/Dockerfile
    environment:
      TZ: 'Europe/Berlin'
      BACKEND_SERVER: http://raspberrypi:8081
    ports:
      - "8080:8080"
    links:
      - api_backend:api_backend
    privileged: true
    networks:
      - backend

  api_backend:
    build: 
      context: .
      dockerfile: ./docker/arm/node-backend/Dockerfile
    ports:
     - "8081:8081"
    networks:
      - backend

networks:
  backend:
