version: '2.2'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/arm/node-frontend/Dockerfile
      args:
        vue_app_backend_api_url: '"http://10.3.141.1:8081"'
    environment:
      TZ: 'Europe/Berlin'
    ports:
      - "8080:8080"
    links:
      - api_backend:api_backend
      - rfid_reader:rfid_reader
    privileged: true
    networks:
      - backend

  api_backend:
    build: 
      context: .
      dockerfile: ./docker/arm/node-backend/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - fridgydatabase:/database
    networks:
      - backend

  rfid_reader:
    build:
      context: .
      dockerfile: ./docker/arm/rfid-reader/Dockerfile
    read_only: true
    privileged: true
    networks:
      - backend

volumes:
  fridgydatabase:

networks:
  backend:
