version: '2'
services:

  web:
    build:
      context: .
      dockerfile: ./docker/arm/node-frontend/Dockerfile
      args:
        vue_app_backend_api_url: '"http://raspberrypi:8081"'
    environment:
      TZ: 'Europe/Berlin'
    ports:
      - "8080:8080"
    links:
      - api_backend:api_backend
      # - rfid_reader:rfid_reader
    privileged: true
    networks:
      - backend

  api_backend:
    build: 
      context: .
      dockerfile: ./docker/arm/node-backend/Dockerfile
    ports:
     - "8081:8081"
    networks:
      - backend

  rfid_reader:
    build: https://github.com/simonneutert/MFRC522-python.git
    networks:
      - backend


networks:
  backend:
