version: '3.4'
services:

  web:
    build:
      context: .
      dockerfile: ./docker/node-frontend/Dockerfile
    environment:
      TZ: 'Europe/Berlin'
    ports:
      - "8080:8080"
    links:
      - backend:backend
    volumes:
      - .:/fridgy-frontend
    privileged: true
    networks:
      - backend

  backend:
    build: ./docker/node-backend/Dockerfile
    networks: 
      - backend


networks: 
  backend: